### PR TITLE
US2164: TA6859: Upgrade SQLite to version 3.24.0

### PR DESCRIPTION
**Pull request by JNiewiadomski**
[US2164](https://rally1.rallydev.com/#/3835160186ud/detail/userstory/215969403428): [TA6859](https://rally1.rallydev.com/#/3835160186ud/detail/task/228767301940): This PR picks up the latest drop of SQLite from [SQLite Download Page](https://www.sqlite.org/download.html).

### CODE REVIEW

**Comment by jake-freeman** [comment]
> +36,759  −9,725 

So you're saying there's been a few changes then

**Comment by mattdicarlo** [comment]
more green than red, reject

**Comment by JNiewiadomski** [comment]
Well, it would be `+35,409 −8,375` if you ignore whitespace

**Comment by JNiewiadomski** [comment]
Good to go. Just made sure debug and release built clean for BBB and VM.

**Comment by jake-freeman** [comment]
Would it be worth try a BlackBox Test run before merging? I guess we could just as easily have Jenkins do it after

**Comment by JNiewiadomski** [comment]
What would be involved to have Jenkins automatically run this through our quality gates?

**Comment by jake-freeman** [comment]
After merging I can just manually kick off a blackbox run against master

**Comment by JNiewiadomski** [comment]
I presume there is a way to have the same set run against `sqlite3` PR's just like against `xl` PR's automatically?

**Comment by jake-freeman** [comment]
I imagine we could

**Comment by jake-freeman** [comment]
BB Tests look good (http://jenkins.vorne.io/job/black-box/12685/console) 

Only 2 failures and they are common!

**Comment by JNiewiadomski** [comment]
Excellent. Thanks for following up Jake!

**Pull request merged**
